import platform

print("Jalondi - SCons Script!")
print("(c) Jeroen P. Broks")
print("Platform: %s\n"%platform.system())

Linux = platform.system()=="Linux"
Windows = platform.system()=="Windows"

JalondiIncludeDirs = [
    "../../../Libs/JCR6/Headers",
    "../../../Libs/Units/Headers",
	"../../../Libs/Lunatic"	
]


if Linux:
    print("Configuring zlib")              
    zlibdir = "../../Libs/JCR6/3rdParty/3rdParty/zlib/src"
    zlibout = "../../Libs/JCR6/3rdParty/3rdParty/zlib/linux"
    zlibsrc = Glob(zlibdir+"/*.c")
    print("Glob(\"%s\"):"%zlibdir) for f in zlibsrc: print("\t%f",f) # debug
    VariantDir(zlibdir, zlibout , duplicate=False)
    StaticLibrary(zlibout+"/zlib_linux",zlibsrc)
    zlib = zlibout+"/zlib_linux"
elif Windows:
    zlib = "../../Libs/JCR6/3rdParty/3rdParty/zlib/zlib"
else:
    print("\x1b[31mERROR!\x1b[0m Running on unknown platform")
    
    